//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.cities = new HashSet<city>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public int ContinentId { get; set; }
        public string Region { get; set; }
        public decimal SurfaceArea { get; set; }
        public Nullable<short> IndepYear { get; set; }
        public int Population { get; set; }
        public Nullable<decimal> LifeExpectancy { get; set; }
        public Nullable<decimal> GNP { get; set; }
        public Nullable<decimal> GNPOld { get; set; }
        public string LocalName { get; set; }
        public string GovernmentForm { get; set; }
        public string HeadOfState { get; set; }
        public Nullable<int> Capital { get; set; }
        public string Code2 { get; set; }
    
        public virtual continent continent { get; set; }
        public virtual ICollection<city> cities { get; set; }
    }
}
